version: '3.1'

services:
  postgresql:
    image: postgres
    restart: always
    ports: 
     - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: photo